# Generated by Django 5.0.3 on 2024-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('uids', models.IntegerField()),
                ('server', models.CharField(max_length=10)),
            ],
        ),
    ]
