# Generated by Django 5.0.3 on 2024-03-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGI', '0002_e_adventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_abiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_nombre', models.CharField(max_length=15)),
                ('pj_elemento', models.CharField(max_length=10)),
                ('pj_lv', models.IntegerField()),
                ('fecha_abismo', models.DateField()),
                ('paso', models.BooleanField()),
            ],
        ),
    ]
