# Generated by Django 5.0.3 on 2024-03-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGI', '0003_e_abiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_abiss',
            name='pj_elemento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='e_abiss',
            name='pj_lv',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='e_abiss',
            name='pj_nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='e_adventure',
            name='pj_elemento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='e_adventure',
            name='pj_lv',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='e_adventure',
            name='pj_nombre',
            field=models.CharField(max_length=40),
        ),
    ]
