# Generated by Django 5.0.3 on 2024-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGI', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='artefactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_nombre', models.CharField(max_length=30)),
                ('pluma', models.CharField(max_length=40)),
                ('reloj', models.CharField(max_length=40)),
                ('gorro', models.CharField(max_length=40)),
                ('copa', models.CharField(max_length=40)),
                ('flor', models.CharField(max_length=40)),
                ('lv_general', models.IntegerField()),
            ],
        ),
    ]
